export const upcomingFights = [
  // UFC Fight Night: Muhammad vs. Bonfim — Jun 6, 2026
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Main',
    tagColor: 'text-blue-400',
    f1: 'Belal Muhammad',
    f1Record: '24-5-0',
    f2: 'Gabriel Bonfim',
    f2Record: '19-1-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Co-Main',
    tagColor: 'text-blue-400',
    f1: 'Brendan Allen',
    f1Record: '25-5-0',
    f2: 'Edmen Shahbazyan',
    f2Record: '14-4-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Featured',
    tagColor: 'text-blue-400',
    f1: 'Fares Ziam',
    f1Record: '18-4-0',
    f2: 'Tom Nolan',
    f2Record: '10-1-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Featured',
    tagColor: 'text-blue-400',
    f1: 'Bryce Mitchell',
    f1Record: '18-3-0',
    f2: 'Santiago Luna',
    f2Record: '8-0-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Featured',
    tagColor: 'text-blue-400',
    f1: 'Iwo Baraniewski',
    f1Record: '13-3-0',
    f2: 'Junior Tafa',
    f2Record: '8-3-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Prelim',
    tagColor: 'text-blue-400',
    f1: 'Matt Schnell',
    f1Record: '17-10-0',
    f2: 'Alessandro Costa',
    f2Record: '9-3-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Prelim',
    tagColor: 'text-blue-400',
    f1: 'Marcus McGhee',
    f1Record: '13-5-0',
    f2: 'John Yannis',
    f2Record: '8-2-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Prelim',
    tagColor: 'text-blue-400',
    f1: 'Bruno Silva',
    f1Record: '23-9-1',
    f2: 'Edgar Chairez',
    f2Record: '12-5-0',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Prelim',
    tagColor: 'text-blue-400',
    f1: 'Jordan Leavitt',
    f1Record: '14-4-0',
    f2: 'Joanderson Brito',
    f2Record: '19-5-1',
  },
  {
    event: 'UFC Fight Night: Muhammad vs. Bonfim',
    date: 'Jun 6, 2026 · Meta APEX, Las Vegas',
    tag: 'Prelim',
    tagColor: 'text-blue-400',
    f1: 'Priscila Cachoeira',
    f1Record: '12-5-0',
    f2: 'Chelsea Chandler',
    f2Record: '11-4-0',
  },

  // UFC Freedom 250 — Jun 7, 2026
  {
    event: 'UFC Freedom 250',
    date: 'Jun 7, 2026 · Washington D.C.',
    tag: 'Main',
    tagColor: 'text-red-500',
    f1: 'Ilia Topuria',
    f1Record: '22-7-1',
    f2: 'Justin Gaethje',
    f2Record: '17-6-1',
  },
  {
    event: 'UFC Freedom 250',
    date: 'Jun 7, 2026 · Washington D.C.',
    tag: 'Co-Main',
    tagColor: 'text-red-500',
    f1: 'Alex Pereira',
    f1Record: '19-7-0',
    f2: 'Ciryl Gane',
    f2Record: '23-4-1',
  },
  {
    event: 'UFC Freedom 250',
    date: 'Jun 7, 2026 · Washington D.C.',
    tag: 'Featured',
    tagColor: 'text-red-500',
    f1: "Sean O'Malley",
    f1Record: '20-3-0',
    f2: 'Aiemann Zahabi',
    f2Record: '9-1-0',
  },
  {
    event: 'UFC Freedom 250',
    date: 'Jun 7, 2026 · Washington D.C.',
    tag: 'Featured',
    tagColor: 'text-red-500',
    f1: 'Josh Hokit',
    f1Record: '21-6-0',
    f2: 'Derrick Lewis',
    f2Record: '12-6-0',
  },
  {
    event: 'UFC Freedom 250',
    date: 'Jun 7, 2026 · Washington D.C.',
    tag: 'Featured',
    tagColor: 'text-red-500',
    f1: 'Mauricio Ruffy',
    f1Record: '22-6-0',
    f2: 'Michael Chandler',
    f2Record: '22-8-0',
  },
  {
    event: 'UFC Freedom 250',
    date: 'Jun 7, 2026 · Washington D.C.',
    tag: 'Featured',
    tagColor: 'text-red-500',
    f1: 'Diego Lopes',
    f1Record: '26-10-0',
    f2: 'Steve Garcia',
    f2Record: '19-7-0',
  },
]