export default function MethodologyPage() {
  const sectionTitle = {
    color: "var(--text-primary)",
  } as const;
  const body = {
    color: "var(--text-secondary)",
  } as const;
  const card = {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
  } as const;

  return (
    <div className="flex flex-col gap-5">
      <div className="rounded-xl px-4 py-4" style={card}>
        <p className="text-sm leading-relaxed" style={body}>
          FightAI is built on one rule: the numbers say what the model actually
          believes, not what looks confident. Every stat on this site is
          explained below — including the places our models disagree with each
          other, and the places we haven&apos;t proven an edge yet.
        </p>
      </div>

      <section>
        <h2 className="text-sm font-bold mb-2" style={sectionTitle}>
          Fighter Rating
        </h2>
        <p className="text-sm leading-relaxed" style={body}>
          A Glicko-2 rating, the same family of rating system used in chess and
          other head-to-head sports. It updates after every fight based on the
          result and the strength of the opponent. The percentile shown
          alongside it (e.g. &quot;top 3%&quot;) compares that fighter against
          everyone else in the database, not just their own weight class.
        </p>
      </section>

      <section>
        <h2 className="text-sm font-bold mb-2" style={sectionTitle}>
          Win probability
        </h2>
        <p className="text-sm leading-relaxed" style={body}>
          Generated by a separate model trained on historical fight data —
          strikes, takedowns, physical attributes, recent form, and more. This
          number is a probability estimate, not a betting recommendation. See
          Calibration below for how honest that probability actually is.
        </p>
      </section>

      <section>
        <h2 className="text-sm font-bold mb-2" style={sectionTitle}>
          Performance Radar
        </h2>
        <p className="text-sm leading-relaxed mb-2" style={body}>
          Four ways of viewing the same underlying stats, shown as a percentile
          against the rest of the division:
        </p>
        <ul
          className="text-sm leading-relaxed flex flex-col gap-1.5 pl-4"
          style={body}
        >
          <li>
            <span style={sectionTitle}>Raw</span> — unadjusted career stats.
          </li>
          <li>
            <span style={sectionTitle}>Discipline</span> — stats broken out by
            skill area (striking, wrestling, BJJ, etc).
          </li>
          <li>
            <span style={sectionTitle}>Defense</span> — how well a fighter
            limits what opponents do to them.
          </li>
          <li>
            <span style={sectionTitle}>Adjusted</span> — performance relative to
            what opponents typically allow, so beating a tough defender counts
            for more.
          </li>
        </ul>
      </section>

      <section>
        <h2 className="text-sm font-bold mb-2" style={sectionTitle}>
          Method of victory
        </h2>
        <p className="text-sm leading-relaxed" style={body}>
          Modeled independently from the win probability above. That means
          method percentages (KO/TKO, Submission, Decision) are not constrained
          to sum to the overall win probability — they answer a different
          question (if this fighter wins, how?) rather than feeding off the win
          model directly. Treat them as separate estimates, not a further
          breakdown of the win percentage.
        </p>
      </section>

      <section>
        <h2 className="text-sm font-bold mb-2" style={sectionTitle}>
          Model accuracy vs. Vegas
        </h2>
        <p className="text-sm leading-relaxed" style={body}>
          The homepage compares our model&apos;s pick accuracy against how often
          Vegas favorites actually win. These two numbers use different time
          windows on purpose: the model&apos;s figure is restricted to recent,
          out-of-sample fights so it can&apos;t be inflated by fights it trained
          on, while the Vegas figure uses a longer 5-year window for a more
          stable baseline. This is an accuracy comparison, not a profitability
          claim — see Calibration for why those are different things.
        </p>
      </section>

      <section>
        <h2 className="text-sm font-bold mb-2" style={sectionTitle}>
          Calibration
        </h2>
        <p className="text-sm leading-relaxed" style={body}>
          The Calibration page measures whether the model&apos;s stated
          confidence matches reality — when it says 70%, does that fighter
          actually win about 70% of the time? That&apos;s a measure of honesty,
          not of profitability.
        </p>
      </section>
    </div>
  );
}
